### ISSUE TITLE
[bug] `get -r` stops after encountering an error

### ISSUE THREAD

**Issue by ret2src** [p0dalirius/smbclient-ng#100]
As the title says, I tried to download the whole `SYSVOL` from a DC, but the download stopped once an error was encountered:

``` text
[error] [!] SMB Error: SMB SessionError: STATUS_ACCESS_DENIED({Access Denied} A process has requested access to an object but has not been granted those access rights.)
```

I think recursively downloading a directory should ignore errors like that and continue with the other files and subdirectories.

**Comment by p0dalirius** [comment]
Fixed in next release

![image](https://github.com/user-attachments/assets/b78f04bf-4a07-4eb9-ab80-3b0f0aa13be2)
