### ISSUE TITLE
[discussion] Merging Find Module and Tree Function

### ISSUE THREAD

**Issue by ghecko** [p0dalirius/smbclient-ng#109]
Hello,

I’ve noticed that the functionality of the `Tree` function and the `Find` module are quite similar. In fact, the `Tree` function could potentially be implemented by calling the `Find` module with the `name` and `iname` parameters left empty.

Would it be beneficial to consider merging these two, or restructuring `Tree` to utilize the `Find` module for more consistent behavior and code reusability? I’d love to hear your thoughts on this.

**Comment by p0dalirius** [comment]
Hi,

Thank you for this suggestion! Initially I wrote only the `tree` function before writing the generic `find` function. 

Having looked at the code of the `tree` function: https://github.com/p0dalirius/smbclient-ng/blob/50344195e6baca14bb47474c5cc1b01cbe710dd0/smbclientng/core/SMBSession.py#L1095-L1263
I agree with you I could be better to use the find function and use a callback function for printing.

The only problem I see for now is to be able to follow the indentation marks in the recursive calls. Right now it is given in argument to the functions as a list of strings. I think for this reason it would be complicated to base the `tree` function on the `find` function easily right now.

Best regards,

**Comment by ghecko** [comment]
Hi,

Thank you for the response! I understand the challenge you're mentioning.

I'll take a closer look to see if there's a way to address this.

Best regards,
