### ISSUE TITLE
[bug] File deletion issue (wildcard vs name)

### ISSUE THREAD

**Issue by ret2src** [p0dalirius/smbclient-ng#113]
I just experienced a weird issue deleting files.
Deleting them using the filename, I run into an issue.
Deleting them using a wildcard, it works.

![Wildcard vs filename issue](https://github.com/user-attachments/assets/cae1da17-16b7-47de-b16e-58a8e294cc88)

In `impacket-smbclient`, deleting the files by name works.

(smbclient-ng version 2.1.6)

**Comment by p0dalirius** [comment]
Thank you for this detailed test case, I will try it on my side and fix what needs to be

**Comment by ghecko** [comment]
I have checked quickly, it seems that the `path_isfile` function used by the rm module need a fullpath from root, however in the command_rm function, only the path provided by the user is passed to the function, so it actually work only for deleting files within the root directory, unless fullpath is provided by the user

**Comment by QU35T-code** [comment]
Cool ! Can this issue be closed ?
