### ISSUE TITLE
[enhancement] Add remote find 'find' command

### ISSUE THREAD

**Issue by tigre-bleu** [p0dalirius/smbclient-ng#16]
An alternative to unix `find` command on the remote server could be handy.

For instance, something like this to recursively search for Firefox user profiles:

```
[\\10.2.54.2\C$\Users]> find -r -type d -name "Mozilla"
```

**Comment by p0dalirius** [comment]
Hello,

It is implemented in a separate module:

`module find -h`

Best regards,

**Comment by tigre-bleu** [comment]
Ha, RTFM like they say :)
