### ISSUE TITLE
[bug] Command 'ls' not able to use a given directory

### ISSUE THREAD

**Issue by Hackndo** [p0dalirius/smbclient-ng#3]
Hello,
Thanks for this great tool.
I'm not sure if this should be supported (and then there's a bug), or if `ls` is only for current directory, and is not expecting any argument

![image](https://github.com/p0dalirius/smbclient-ng/assets/11051803/af41931d-1e74-48f9-9913-9abf796a13c0)

In any case, it would be very useful to be able to list a directory providing its name (or its path)

Again thank you for the tool :)

**edit**: It seems[ it should be able to list a directory provided as an argument](https://github.com/p0dalirius/smbclient-ng/blob/main/smbclientng/core/InteractiveShell.py#L501)

**Comment by p0dalirius** [comment]
Hey!

You are absolutely right, this is a bug. Thank you for the PR!

Best regards,
