### ISSUE TITLE
[question] file compression and mount capability

### ISSUE THREAD

**Issue by jdivincuit** [p0dalirius/smbclient-ng#6]
Thanks for this great project master poda. 
2 features suggestions that I missed the lot in `smbclient.py`:
- compression command for file or directories
- a command to mount the SMB share on the local filesystem (like with `mount.cifs`). 
  example usage: `mount C$ /mnt/disk`

**Comment by p0dalirius** [comment]
Hi!

Thank you for the feedback!

I have created an issue and it will be implemented in future versions:

 - #7 a command to mount the SMB share on the local filesystem (like with `mount.cifs`). 
  example usage: `mount C$ /mnt/disk`

I don't fully understand what you mean by _compression command for file or directories_. Can you detail it a lot?

Best regards,

**Comment by jdivincuit** [comment]
Hi, thanks for your answer!
The compression command would allow you to compress files remotely using a native Windows compression library.
This would save time compared with recursive downloading of a large file, in a redteam context having significant network constraints. 
Example of use: compress C:\dir\archive.zip C\folder\source

**Comment by p0dalirius** [comment]
Okay this is what I understood.

I think this is impossible without executing code on the remote machine with psexec / smbexec / atexec etc...
