### ISSUE TITLE
 [enhancement] Features suggestions: find, output tree to a file, Case insensitivity, Remove the need to quote spaces in paths

### ISSUE THREAD

**Issue by jdivincuit** [p0dalirius/smbclient-ng#76]
Thanks for this tool, I've just tested the new release. 
Some suggestions: 

- `find` command: would allow to search for files in the share, with wildcard search functionality. E.g: `find ./Users "*.zip"`

- Silent tree: possibility of making a `tree` without visual output, only dump the result in a file. Can be used to map a folder to  search/grep for files offline, in order to then fetch directly what you need without spending time searching from `smbclient-ng` (especially if the `find` function is difficult to implement)

- Case insensitivity: Windows is case insensitive. Although auto-completion corrects case on `smbclient-ng`, this assumes TTY interactivity, which is not always the case. Case insensitivity in `smbclient.py` was appreciated

- Remove the need to quote spaces in paths: `smbclient.py` didn't need to quote spaces in paths, which was appreciated

Thanks for your time, let me know if this seems useful/doable (?)

**Comment by p0dalirius** [comment]
Hi,

I hope you are well,

---

> `find` command: would allow to search for files in the share, with wildcard search functionality. E.g: `find ./Users "*.zip"`

Already implemented in a module, `module find ./ -type f -iname '*.xml'`, I can create an alias `find` --> `module find` if it is clearer.

![image](https://github.com/p0dalirius/smbclient-ng/assets/79218792/3dde33a9-ee45-4294-8530-05898e529ac3)

---

> Silent tree: possibility of making a `tree` without visual output, only dump the result in a file. Can be used to map a folder to  search/grep for files offline, in order to then fetch directly what you need without spending time searching from `smbclient-ng` (especially if the `find` function is difficult to implement)

I did not think of that, and personally I would not find it useful but I understand your use case, I will implement it on `find` and `tree`

---

> Case insensitivity: Windows is case insensitive. Although auto-completion corrects case on `smbclient-ng`, this assumes TTY interactivity, which is not always the case. Case insensitivity in `smbclient.py` was appreciated

I intended it to be case insensitive, I will correct it

---

> Remove the need to quote spaces in paths: `smbclient.py` didn't need to quote spaces in paths, which was appreciated

I will not change this, as it is impossible to parse commands without it. I am using `shlex` to parse and autoquote commands. This allows to pass multiple files in arguments to commands, such as `get 'File 1.txt' 'File 2.txt'`. It has the same syntax as bash shells

---

Best regards,
