### ISSUE TITLE
[documentation] README example.png : Parameter --target replaced by --host

### ISSUE THREAD

**Issue by k8pl3r-sh** [p0dalirius/smbclient-ng#91]
Hello ! I think that the example picture of the README.md file (`smbclient-ng/.github/example.png`) has a typo on the `--target` parameter which is not used in the parsing of args. I think that it should be replaced by the parameter `--host` ?

I don't have a convenient lab to PR a new picture

**Comment by p0dalirius** [comment]
Good catch, I will screen a new one !
