### ISSUE TITLE
[bug] Pass-the-Hash not working correctly

### ISSUE THREAD

**Issue by ret2src** [p0dalirius/smbclient-ng#95]
During a pentest I've noticed that passing the hash to access SMB shares does not work correctly.

The following works:

```bash
impacket-smbclient SERVICE_ADDS@SERVER123.DOMAIN.LOCAL  -hashes :[REDACTED]
```
While the following does not:

```bash
smbclientng -d domain.local -u 'service_adds' --host SERVER123  --hashes ':[REDACTED]'
```

**Comment by p0dalirius** [comment]
Hi,

Working on it. I have added debug messages to better see what is going on. It works well with pass the hash in format `LM:NT` :

```
./smbclient-ng.py -u Administrator -H 'aad3b435b51404eeaad3b435b51404ee:520126a03f5d5a8d836f1c4f34ede7ce' -d OPENPHARMA --host 10.217.51.101  --debug
```

![image](https://github.com/user-attachments/assets/2e53f78f-1ba2-4b2e-a47e-b3afe1cc4b46)

But it crashes with format `:NT`:

![image](https://github.com/user-attachments/assets/36a7fb72-0120-40be-92b2-f9dbf72aef49)

I think I have a problem in the parsing of hashes

Best regards,

**Comment by ret2src** [comment]
Awesome, thank you for the rapid fix and great project! Looking forward to spice up my SMB enum with it in the future!
